import { motion } from 'framer-motion'
import { useState, useEffect } from 'react'
import { Sparkles, Zap, Check, Star, FileText, TrendingUp, Globe, Search, BarChart, ChevronDown, Lock } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useArticles } from '../hooks/useArticles'
import { useAuth } from '../hooks/useAuth'
import AuthModal from '../components/auth/AuthModal'
import { toast } from 'react-hot-toast'

export default function Home() {
  const [topic, setTopic] = useState('')
  const [websiteUrl, setWebsiteUrl] = useState('')
  const [showAuthModal, setShowAuthModal] = useState(false)
  const [openFaq, setOpenFaq] = useState(null)
  const { generateArticle, generating } = useArticles()
  const { user, usage, canGenerate, checkAuth } = useAuth()
  const navigate = useNavigate()

  useEffect(() => {
    checkAuth()
  }, [checkAuth])

  const canCreate = canGenerate()
  const isDemoUser = !user
  const demoUsed = usage?.demo?.used

  const handleGenerate = async (e) => {
    e.preventDefault()
    if (!topic.trim()) return

    if (!canCreate) {
      if (isDemoUser) {
        toast.error('Demo limit reached! Sign up for 1 article/day free.', { duration: 5000 })
        setShowAuthModal(true)
      } else {
        toast.error('Daily limit reached! Upgrade to Pro for 15 articles/day.', { duration: 5000 })
      }
      return
    }

    try {
      await generateArticle(topic, websiteUrl)
      navigate('/article/new')
    } catch (error) {
      if (error.message.includes('Demo limit') || error.message.includes('month')) {
        setShowAuthModal(true)
      } else if (error.message.includes('Sign in') || error.message.includes('Unauthorized')) {
        setShowAuthModal(true)
      }
    }
  }

  const faqs = [
    {
      q: "What makes SEOScribe different from other AI writers?",
      a: "SEOScribe generates complete articles with citations, hero images, internal links, FAQs, and social media posts - all optimized for SEO. We research top-ranking content to create articles that actually rank."
    },
    {
      q: "How does the free plan work?",
      a: "Free users get 1 article per day and 1 use of each SEO tool per day. No credit card required. Upgrade to Pro anytime for 15 articles/day and 10 tool uses per tool/day."
    },
    {
      q: "Can I try it without signing up?",
      a: "Yes! You can generate 1 demo article per month without creating an account. After that, sign up for 1 free article per day."
    },
    {
      q: "What AI models do you use?",
      a: "We use Claude 3.5 Sonnet for article generation and Gemini 2.5 Flash for image generation, ensuring the highest quality content and visuals."
    },
    {
      q: "Can I use the articles commercially?",
      a: "Yes! You own all content generated by SEOScribe. Use it on your blog, client projects, or anywhere else without restrictions."
    },
    {
      q: "Do the articles include real research?",
      a: "Yes! We use Serper API to research top-ranking content for your topic, analyze competitor articles, and cite authoritative sources automatically."
    },
    {
      q: "Can I cancel my Pro subscription anytime?",
      a: "Absolutely! Cancel anytime through your account settings. No questions asked, no cancellation fees."
    }
  ]

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-20 pb-32 overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0 pointer-events-none">
          <motion.div
            className="absolute top-20 left-10 w-96 h-96 bg-purple-500/20 rounded-full blur-3xl"
            animate={{ 
              scale: [1, 1.2, 1], 
              opacity: [0.3, 0.5, 0.3],
              x: [0, 50, 0],
              y: [0, 30, 0]
            }}
            transition={{ duration: 8, repeat: Infinity }}
          />
          <motion.div
            className="absolute bottom-20 right-10 w-96 h-96 bg-pink-500/20 rounded-full blur-3xl"
            animate={{ 
              scale: [1.2, 1, 1.2], 
              opacity: [0.5, 0.3, 0.5],
              x: [0, -50, 0],
              y: [0, -30, 0]
            }}
            transition={{ duration: 8, repeat: Infinity, delay: 1 }}
          />
          <motion.div
            className="absolute top-1/2 left-1/2 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl"
            animate={{ 
              scale: [1, 1.3, 1], 
              opacity: [0.2, 0.4, 0.2]
            }}
            transition={{ duration: 10, repeat: Infinity, delay: 2 }}
          />
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <motion.div
              className="inline-flex items-center gap-2 px-4 py-2 bg-purple-500/20 border border-purple-500/30 rounded-full mb-6 backdrop-blur-sm"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              whileHover={{ scale: 1.05 }}
            >
              <Star className="w-4 h-4 text-yellow-400 fill-yellow-400 animate-pulse" />
              <span className="text-sm font-bold">Rated #1 AI Writer • 12,000+ Users</span>
            </motion.div>

            <motion.h1
              className="text-5xl lg:text-7xl font-black mb-6 leading-tight"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
            >
              The Best <span className="gradient-text">AI Writer</span>
              <br />for SEO Content
            </motion.h1>

            <motion.p
              className="text-xl text-white/80 max-w-3xl mx-auto mb-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
            >
              Generate <strong className="text-white">proven, rank-ready articles</strong> with citations 
              and images in 90 seconds. Our AI writing tool creates SEO-optimized content that 
              outranks competitors.
            </motion.p>

            <motion.form
              onSubmit={handleGenerate}
              className="max-w-2xl mx-auto glass-strong rounded-2xl p-8 shadow-2xl"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
            >
              {!canCreate && isDemoUser && (
                <div className="mb-4 bg-orange-500/20 border border-orange-500/30 rounded-lg p-3 text-sm">
                  <div className="flex items-center gap-2">
                    <Lock className="w-4 h-4 text-orange-400" />
                    <span className="text-orange-400 font-bold">Demo Used This Month</span>
                  </div>
                  <p className="text-white/70 mt-1">Sign up for 1 free article per day!</p>
                </div>
              )}

              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="Enter your topic (e.g., Best Project Management Tools 2025)"
                className="w-full px-4 py-4 mb-4 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-400/50 transition-all disabled:opacity-50"
                disabled={generating || (!canCreate && isDemoUser)}
              />
              <input
                type="text"
                value={websiteUrl}
                onChange={(e) => setWebsiteUrl(e.target.value)}
                placeholder="Your website URL (optional, for internal links)"
                className="w-full px-4 py-4 mb-4 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-400/50 transition-all disabled:opacity-50"
                disabled={generating || (!canCreate && isDemoUser)}
              />
              <motion.button
                type="submit"
                className="w-full py-4 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg font-bold text-lg shadow-lg shadow-purple-500/50 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                whileHover={{ scale: (generating || (!canCreate && isDemoUser)) ? 1 : 1.02 }}
                whileTap={{ scale: (generating || (!canCreate && isDemoUser)) ? 1 : 0.98 }}
                disabled={generating || !topic.trim() || (!canCreate && isDemoUser)}
              >
                {generating ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    <span>Generating...</span>
                  </>
                ) : !canCreate && isDemoUser ? (
                  <>
                    <Lock className="w-5 h-5" />
                    <span>Sign Up for Free Articles</span>
                  </>
                ) : (
                  <>
                    <Zap className="w-5 h-5" />
                    <span>Generate Article Now - Free</span>
                  </>
                )}
              </motion.button>
              <p className="text-white/60 text-sm mt-4">
                {isDemoUser 
                  ? demoUsed 
                    ? "Demo used. Sign up for 1 free article/day!"
                    : "Try free: 1 demo article/month • Sign up: 1 article/day"
                  : "Free forever: 1 article/day • Pro: 15/day + unlimited exports"
                }
              </p>
            </motion.form>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl font-black mb-4">Why Choose Our AI Writer</h2>
            <p className="text-xl text-white/70">
              Everything you need to create, optimize, and publish SEO content
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: FileText,
                title: 'Complete Content Packages',
                description: 'Get articles with citations, images, FAQs, and social posts - everything ready to publish',
                color: 'from-purple-500 to-pink-500'
              },
              {
                icon: Check,
                title: 'SEO-Optimized Structure',
                description: 'Proper headings, meta descriptions, keyword placement, and readability optimization',
                color: 'from-blue-500 to-cyan-500'
              },
              {
                icon: TrendingUp,
                title: 'Proven to Rank',
                description: 'Our AI writer creates content that actually ranks on Google and drives organic traffic',
                color: 'from-green-500 to-emerald-500'
              }
            ].map((feature, i) => (
              <motion.div
                key={feature.title}
                className="glass rounded-2xl p-8 hover:scale-105 transition-transform"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <div className={`w-16 h-16 bg-gradient-to-br ${feature.color} rounded-xl flex items-center justify-center mb-4`}>
                  <feature.icon className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-white/70">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Advanced Features */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl font-black mb-4">Advanced AI Features</h2>
            <p className="text-xl text-white/70">
              Powered by cutting-edge AI models for maximum quality
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: Search,
                title: 'Real-Time Research',
                description: 'Scrapes and analyzes top-ranking content to create better articles',
              },
              {
                icon: Globe,
                title: 'Auto Internal Links',
                description: 'Scans your website and adds relevant internal links automatically',
              },
              {
                icon: BarChart,
                title: 'Competitor Analysis',
                description: 'Analyzes competitors and identifies content gaps to outrank them',
              }
            ].map((feature, i) => (
              <motion.div
                key={feature.title}
                className="glass rounded-2xl p-8 hover:scale-105 transition-transform"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-xl flex items-center justify-center mb-4">
                  <feature.icon className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-white/70">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20 bg-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl font-black mb-4">Simple, Transparent Pricing</h2>
            <p className="text-xl text-white/70">
              Start free, upgrade when you need more
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {/* Free Plan */}
            <motion.div
              className="glass rounded-2xl p-8"
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h3 className="text-2xl font-bold mb-2">Free</h3>
              <div className="text-4xl font-black mb-6">
                $0<span className="text-lg font-normal text-white/60">/month</span>
              </div>
              <ul className="space-y-4 mb-8">
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>1 article per day</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>SEO-optimized structure</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Citations & sources</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>FAQs & social posts</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Hero images included</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>1 SEO tool use per tool/day</span>
                </li>
              </ul>
              <motion.button
                onClick={() => !user && setShowAuthModal(true)}
                className="w-full py-3 bg-white/10 border border-white/20 rounded-lg font-bold hover:bg-white/20 transition-colors"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                {user ? 'Current Plan' : 'Get Started Free'}
              </motion.button>
            </motion.div>

            {/* Pro Plan */}
            <motion.div
              className="glass-strong rounded-2xl p-8 border-2 border-purple-500/50 relative"
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <div className="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full text-sm font-bold">
                MOST POPULAR
              </div>
              <h3 className="text-2xl font-bold mb-2">Pro</h3>
              <div className="text-4xl font-black mb-6">
                $24<span className="text-lg font-normal text-white/60">/month</span>
              </div>
              <ul className="space-y-4 mb-8">
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span className="font-bold">15 articles per day</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Everything in Free</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Unlimited exports</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Priority AI generation</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>10 SEO tool uses per tool/day</span>
                </li>
                <li className="flex items-start gap-3">
                  <Check className="w-5 h-5 text-green-400 flex-shrink-0 mt-1" />
                  <span>Advanced analytics</span>
                </li>
              </ul>
              <motion.button
                onClick={() => user ? navigate('/dashboard') : setShowAuthModal(true)}
                className="w-full py-3 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg font-bold shadow-lg"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                {user ? 'Upgrade to Pro' : 'Get Started Free'}
              </motion.button>
            </motion.div>
          </div>
        </div>
      </section>

      {/* FAQs Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl font-black mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-white/70">
              Everything you need to know about SEOScribe
            </p>
          </motion.div>

          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                className="glass rounded-xl overflow-hidden"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
                >
                  <span className="font-bold text-lg">{faq.q}</span>
                  <ChevronDown 
                    className={`w-5 h-5 transition-transform ${openFaq === i ? 'rotate-180' : ''}`}
                  />
                </button>
                {openFaq === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="px-6 pb-4"
                  >
                    <p className="text-white/70">{faq.a}</p>
                  </motion.div>
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {showAuthModal && <AuthModal onClose={() => setShowAuthModal(false)} />}
    </div>
  )
}
